FROM golang:1.26.2-alpine

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@$(go list -m -f '{{.Version}}' github.com/air-verse/air)

COPY . .

EXPOSE 8080

CMD ["air"]